export const TASKS_ACTION_REQUEST = 'TASKS_ACTION_REQUEST';
export const TASKS_ACTION_FAIL = 'TASKS_ACTION_FAIL';
export const RESET_STATE_ACTION = 'RESET_STATE_ACTION';

export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

export const SET_FILTER = 'SET_FILTER';
